input: [256, 52]
output: 6

sequence:
  - block: "conv_1"
    op_candidates: "conv1d"
    type_repeat:
      type: "vary_all"
      depth: [3]

  - block: "pool_1"
    op_candidates: "maxpool"

  - block: "conv_2"
    op_candidates: "conv1d"
    type_repeat:
      type: "vary_all"
      depth: [3]

  - block: "lstm"
    op_candidates: "lstm"

  - block: "dropout"
    op_candidates: "dropout"

  - block: "linear"
    op_candidates: "linear"
    type_repeat:
      type: "vary_all"
      depth: [2]

default_op_params:
  conv1d:
    kernel_size: [9]
    stride: [1]
    out_channels: [128]
    padding: "same"

  maxpool:
    kernel_size: [4]
    stride: [2]

  lstm:
    hidden_size: [128]
    num_layers: [2]
    bidirectional: [True]
    batch_first: True

  linear:
    width: [128]
    activation: ["relu"]

  dropout:
    p: [0.5]

  gaussian_dropout:
    p: [0.5]
